name: "Chromatic"

on: push

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: 24.19.0
      - uses: pnpm/action-setup@v6
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install
      - name: Run Chromatic
        uses: chromaui/action@37b88badc3a1122c01861af329554d8a227d7e52 #v18.4.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: false
          buildScriptName: "storybook:build"